### ISSUE TITLE
Blizzard_SharedTalentFrame.lua:547: attempt to call field 'getSpecializedChoiceMixin' (a table value)

### ISSUE THREAD

**Issue by Thrumbar** [kurapica/EnhanceBattlefieldMinimap#3] opened 2023-05-06 00:40 UTC
This error pops when mousing over dragonflight talents.  Dragon isles Summery,  View,  4th  and the 8th one down.  The popup to select which talent you can choose between them does nor show with addon active.  Have to unload it to make selection.

82x ...izzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:547: attempt to call field 'getSpecializedChoiceMixin' (a table value)
[string "@Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua"]:547: in function `GetSpecializedSelectionChoiceMixin'
[string "@Blizzard_SharedTalentUI/Blizzard_SharedTalentSelectionTemplates.lua"]:61: in function `SetSelectionOptions'
[string "@Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua"]:567: in function `ShowSelections'
[string "@Blizzard_SharedTalentUI/Blizzard_SharedTalentButtonTemplates.lua"]:1245: in function `ShowSelections'
[string "@Blizzard_SharedTalentUI/Blizzard_SharedTalentButtonTemplates.lua"]:1196: in function <...redTalentUI/Blizzard_SharedTalentButtonTemplates.lua:1184>

Locals:
self = GenericTraitFrame {
 0 = <userdata>
 CascadeRepurchaseRanks = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:1350
 IsCondInfoCacheDirty = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:941
 AddCostToTooltip = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:1392
 SetSuppressedSounds = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:1283
 RollbackConfig = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:1267
 IsDefinitionInfoCacheDirty = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:929
 RefundRank = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:1354
 SetElementFrameLevel = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:650
 UpdateEdgesByCondition = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:642
 UpdateSelections = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:572
 AttemptConfigOperation = <function> defined @Blizzard_GenericTraitUI/Blizzard_GenericTraitFrame.lua:214
 ForceDefinitionInfoUpdate = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:872
 ForceCondInfoUpdate = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:854
 ShouldHideSingleRankNumbers = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:1021
 getSpecializedChoiceMixin = nil {
 }
 ReleaseAndReinstantiateTalentButton = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:729
 GetTalentTreeID = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:974
 ReportConfigCommitError = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:1326
 ClearCascadeRepurchaseHistory = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:1366
 UnregisterEvents = <function> defined @SharedXML/CallbackRegistry.lua:200
 GetTreeInfoOrLayoutDefaults = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:1009
 OnGateDisplayed = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:1051
 getDisplayTextFromTreeCurrency = <function> defined @Blizzard_GenericTraitUI/Blizzard_GenericTraitFrame.lua:94
 TryPlaySound = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:1277
 leftPadding = 3
 CheckAndReportCommitOperation = <function> defined @Blizzard_GenericTraitUI/Blizzard_GenericTraitFrame.lua:205
 ReleaseTalentDisplayFrame = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:542
 AddEdgeRequirementsToTooltip = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:1465
 Event = <table> {
 }
 UpdateColorBlindModeUI = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:1508
 GetIncomingEdgeInfoForNode = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:1494
 MarkDefinitionInfoCacheDirty = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:909
 MarkTreeDirty = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:1059
 treeCurrencyInfo = <table> {
 }
 ClearInfoCaches = <function> defined @Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua:945
 ShowGenericTraitFrameTutorial = <function> defined @Blizzard_GenericTraitUI/Blizzard_GenericTraitFrame.lua:320
 IsNodeInfoCacheDirty = <function> defined @Bli

**Comment by kurapica** [comment] 2023-10-18 06:37
EBFM won't touch that, maybe caused by the new setting panels taints. Should be fixed by blz self, unless no one can put settings in the control panel.

**Closed as completed by kurapica** 2023-10-18 06:37 UTC
